name = "Nuklear"
uuid = "8d0e9305-38f4-5c97-8ceb-e1429a1a2d0c"
authors = ["Yupei Qi <qiyupei@gmail.com>"]
version = "0.1.1"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
